### ISSUE TITLE
API Gateway Integration - Front end APIs

### ISSUE THREAD

**Issue by ghost** [airavata-courses/Squadron#11]

**Comment by ghost** [comment]
We will have the following APIs in API-Gatway that can be called from the front-end:

## **1. /login**
POST
```
{ 
  username: <> ,
  password: <>
}
```
Response
```
{status: success/failed, token: <> }
```

## 2. /register
POST
```
{ 
  username: <> ,
  password: <>,
  first_name: <>,
  last_name: <>, 
  email: <>
}
```
Response
```
{
status: success/failed, error: {}
}
```
## 3. /create-experiment
POST
```
{ 
  house_area: <> ,
  months: [<>],
  pincode: <>,
}
```
Response
```
{status: success/failed, error: {}, request_id: <>}
```
## 4. /update-experiment
POST
```
{ 
  request_id: <>,
  house_area: <> ,
  months: [<>],
  pincode: <>,
}
```
Response
```
{status: success/failed, error: {}, request_id: <>}
```


## 5. /experiment/<experiment-id>
GET
Response
< To be defined >

## 6. /get-all-experiments
GET
Response 
< To be defined >

**Comment by ghost** [comment]
@aarushiibisht @akhil-8607  
Can you check if we will need any other APIs from the front-end ?

**Comment by akhil-8607** [comment]
All the required API's have been specified ,
