### ISSUE TITLE
Containerize User Management Service

### ISSUE THREAD

**Issue by aarushiibisht** [airavata-courses/Squadron#2]

**Comment by ghost** [comment]
User-management service will provide the following apis:
1. registration,
2. login,
3. verify jwt token,

The details of the user will be saved in MongoDB database. Once the user is authenticated a JWT token will be shared with the user. On subsequent API calls to any other microservice, the JWT token would be verified that is passed by the user. 

https://blog.logrocket.com/how-to-secure-a-rest-api-using-jwt-7efd83e71432/

Out of scope
1. There will not be any roles, and all the authenticated users will have complete access to the all the APIs,
2. No HTTPS will be used. We will pass everything with HTTP.
