### ISSUE TITLE
API Gateway - Back-end API design discussion

### ISSUE THREAD

**Issue by ghost** [airavata-courses/Squadron#22]
#11 #9 

Here we will define the back-end APIs that should be called for each front-end API. I think we need to discuss,
1. Whether we should have a one-to-one mapping between each front-end API to back-end,
2. Whether API gateway can call multiple back-end APIs for a single request from front-end.

If we pick 2nd option we will have to do a lot of coordination between microservices, but if we use API-gateway as an aggregator and processor of data, we can save effort and our microservices won't have much inter-dependence on each other. So I suggest option 2. Let me know if you agree,

**Comment by akhil-8607** [comment]
I would also suggest the second option with using gateway as aggregator and processor of data to decrease the redundant messaging and decrease interdependence of Microservices on each other directly
