### ISSUE TITLE
Info about actively developed branch 

### ISSUE THREAD

**Issue by adithyaselv** [airavata-courses/Squadron#23]
Hi ! I am trying to build and test the project, however I am slightly confused on which branch I must do this. Can you please add a short info on README in master or in wiki about this to get started. (related to #19)

**Comment by aarushiibisht** [comment]
The back end services are available in aarushi-develop branch with instructions in readme

**Comment by adithyaselv** [comment]
Thanks ! I will have a look into it

**Comment by aarushiibisht** [comment]
All the changes can also be verified in the develop branch. Which has been updated to include api server as well

**Comment by adithyaselv** [comment]
Sure I am currently trying to review running the project . can you also add info on how to test ? since there is no UI right now ?
