### ISSUE TITLE
APIs are not standardized - Frontend uses keywords such as house_area, whereas backend uses houseArea

### ISSUE THREAD

**Issue by raj-nandu** [airavata-courses/Squadron#25]

**Comment by aarushiibisht** [comment]
Backend code has been updated

**Comment by ghost** [comment]
Hello @raj-nandu ,

We have fixed this issue in the below pull-request for API gateway. Now all our services are using the same API keys. 

https://github.com/airavata-courses/Squadron/pull/30

**Comment by ghost** [comment]
Fixed, as mentioned above
