### ISSUE TITLE
Data Retrieval Service Implementation

### ISSUE THREAD

**Issue by aarushiibisht** [airavata-courses/Squadron#3]

**Comment by aarushiibisht** [comment]
Data Source public API
https://www.melissa.com/v2/lookups/zipclimate/zipcode/?zipcode=47404&fmt=json

**Comment by akhil-8607** [comment]
we have decided upon the data source  presented in the below   link to get the rain fall data https://www.melissa.com/v2/lookups/zipclimate/zipcode/?zipcode=47404 according to zip code. the  rainfall data is sent to the model Microservice to perform calculations.

**Comment by aarushiibisht** [comment]
**Sample input:**
curl -v -X POST http://localhost:8081/api/v1/request/rain/1221 --data '{"HouseArea": 2, "PinCode": 47408, "Months": [1,3]}'

**Sample output json:**

{"HouseArea":2,"PinCode":47408,"Months":[1,3],"RequestId":"1221","Data":[{"MonthName":"January","HighTemp":36.5,"AvgTemp":27.9,"LowTemp":19.3,"Cdd":0,"Hdd":1151,"Rain":2.66,"Zip":"47408","MonthNumber":1},{"MonthName":"March","HighTemp":52.4,"AvgTemp":42,"LowTemp":31.6,"Cdd":0,"Hdd":713,"Rain":3.66,"Zip":"47408","MonthNumber":3}],"Status":"ok"}

**Comment by ghost** [comment]
Have you guys decided the APIs and how model-execution and data-retrieval will communicate with each other?

**Comment by ghost** [comment]
@aarushiibisht what is the progress on message queue?

**Comment by aarushiibisht** [comment]
Done! @akhil-8607 You can look at the readme in DataRetrieval branch for sample Kafka output. @shivamriky I have updated the readme with the API. API gateway can now use this API to talk to DataRetrievalService

**Comment by aarushiibisht** [comment]
Implementation is completed
