### ISSUE TITLE
Architectural diagram

### ISSUE THREAD

**Issue by gkiran292** [airavata-courses/Squadron#33]
I am trying to understand the system with the help of an architectural diagram. Do you have any architectural diagrams that I can view?

**Comment by ghost** [comment]
Hello,

We are in the process of updating our readme. Meanwhile you can refer the architectural diagram here. It is more of a flow diagram which shows how data is moving between services

![Ass_1 (2)](https://user-images.githubusercontent.com/5948157/74495966-45a09400-4eff-11ea-8556-52300ba422cb.png)

**Comment by ghost** [comment]
Updated the diagram in the wiki
