### ISSUE TITLE
Assignment-2 pre-development steps

### ISSUE THREAD

**Issue by ghost** [airavata-courses/Squadron#40]
1. Complete UI - @akhil-8607  - Tuesday
2. Clean-up issues in github @shivamriky - 23rd Feb
3. Check and update readme/wiki properly - @akhil-8607 - 23rd Feb
4. Dockerize API-gateway - @aarushiibisht - 23rd Feb
5. Dockerize UI 
6. Clean up branches
7. Integration test of UI and all the services.

**Comment by aarushiibisht** [comment]
All the pre development steps are done. Hence closing this issue
