### ISSUE TITLE
Unable to run all the services, docker image deleted

### ISSUE THREAD

**Issue by thumblas** [airavata-courses/Squadron#47]
![squadron](https://user-images.githubusercontent.com/9990210/75956907-e511d080-5e86-11ea-9818-0195125e442f.png)
Docker image  for post-processing deleted from docker hub removed so unable to run all the microservices

**Comment by aarushiibisht** [comment]
Hi,
None of our project images are available in docker hub. We first build our images.
Can you please try to build docker image for post processing service using these commands as mentioned in readme

cd PostProcessing
docker build -t post_processing .

**Comment by thumblas** [comment]
Hi ,

I was able to run it now when i removed all the images and tried again. The same thing didn't work for me yesterday.

Thanks
Shivani
