### ISSUE TITLE
[Peer review] Auto build not visible in jenkins

### ISSUE THREAD

**Issue by gouthamgopal** [airavata-courses/Squadron#72]
Hi Team,

Had commited a small change from github, [commit id](https://github.com/airavata-courses/Squadron/commit/21b0fc4f5f985acce534fa92e349df0f02e14f20).

This was to check the auto deployment feature, but I was unable to spot that through Jenkins, as no build was triggered. Could you please check and update.

Regards,
Goutham Gopal

**Comment by ghost** [comment]
Hi Gopal, We have disabled the build right now as we are running testing.

**Comment by ghost** [comment]
Can you try in 4-5 mins. We are enabling it now

**Comment by gouthamgopal** [comment]
Hi Shivam,

Okay. Saw the pipeline running succesfully in travis for the provided commit.

**Comment by gouthamgopal** [comment]
changes were reflected in the UI as well as visible build success in Jenkins pipeline.
Closing the issue.

Thanks for the spontaneous reply team!
